### ISSUE TITLE
Patient widget in AddSample does not work

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.health#122]
## Steps to reproduce

Go to the creation sample view.

Start writing in the Patient Widget to search for the wanted patient.

## Current behavior

The widget does not display Patients any more.

## Expected behavior

To filter the dropdown list by the search term

**Comment by xispa** [comment]
You need to type 3 characters at least. IMO, does not make sense to allow searches for one or two characters only, especially for patients, that we expect its total number to grow a lot
