### ISSUE TITLE
Error trying to Edit Analysis specifications

### ISSUE THREAD

**Issue by raskimono** [senaite/senaite.health#124]
## Error below

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Shared.DC.Scripts.Bindings, line 322, in __call__
    Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
    Module Products.CMFCore.FSPageTemplate, line 237, in _exec
    Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
    Module Products.PageTemplates.PageTemplate, line 87, in pt_render
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 98, in __call__
    Module z3c.pt.pagetemplate, line 173, in render
    Module chameleon.zpt.template, line 306, in render
    Module chameleon.template, line 209, in render
    Module chameleon.template, line 187, in render
    Module 38a13ada097354ba7db45b2a9304f8be.py, line 813, in render
    Module deb4febaba49dd2d141bf957785027da.py, line 1468, in render_master
    Module deb4febaba49dd2d141bf957785027da.py, line 605, in render_content
    Module 38a13ada097354ba7db45b2a9304f8be.py, line 803, in __fill_content_core
    Module 38a13ada097354ba7db45b2a9304f8be.py, line 176, in render_content_core
    Module 4578e86d79e34dc711ff58d216760b87.py, line 166, in render_body
    Module c28d9dac308d589e74bc934682a30ab8.py, line 1543, in render_view
    Module c28d9dac308d589e74bc934682a30ab8.py, line 872, in render_base_view
    Module c28d9dac308d589e74bc934682a30ab8.py, line 1328, in render_data
    Module e96a5c80ec77753c784febaf10a73f04.py, line 262, in render_view
    Module bika.health.widgets.analysisspecificationwidget, line 84, in AnalysisSpecificationResults
    Module bika.health.widgets.analysisspecificationwidget, line 37, in __init__

TypeError: __init__() takes exactly 3 arguments (5 given) - Expression: "python:widget.AnalysisSpecificationResults(field)" - Filename: ... s/skins/bika/bika_widgets/analysisspecificationwidget.pt - Location: (line 11: col 37) - Source: ... ructure python:widget.AnalysisSpecificationResults(field)"/> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Expression: "widget_view" - Filename: ... gg/Products/Archetypes/skins/archetypes/widgets/field.pt - Location: (line 53: col 30) - Source: <metal:block use-macro="widget_view" /> ^^^^^^^^^^^ - Expression: "data_macro|default" - Filename: ... gg/Products/Archetypes/skins/archetypes/widgets/field.pt - Location: (line 28: col 37) - Source: ... tal:use_data use-macro="data_macro|default" /> ^^^^^^^^^^^^^^^^^^ - Expression: "context/widgets/field/macros/base_view" - Filename: ... gg/Products/Archetypes/skins/archetypes/widgets/field.pt - Location: (line 61: col 42) - Source: ... ew use-macro="context/widgets/field/macros/base_view" /> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Expression: "field_macro" - Filename: ... 8-py2.7.egg/Products/Archetypes/skins/archetypes/base.pt - Location: (line 25: col 42) - Source: <metal:use_field use-macro="field_macro" /> ^^^^^^^^^^^ - Expression: "body_macro" - Filename: ... .7.egg/Products/Archetypes/skins/archetypes/base_view.pt - Location: (line 81: col 35) - Source: <metal:use_body use-macro="body_macro" /> ^^^^^^^^^^ - Expression: "provider:plone.abovecontentbody" - Filename: ... gg/senaite/lims/skins/senaite_templates/main_template.pt - Location: (line 148: col 90) - Source: ... ent="structure provider:plone.abovecontentbody" tal:conditio ... ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Expression: "context/main_template/macros/master" - Filename: ... .7.egg/Products/Archetypes/skins/archetypes/base_view.pt - Location: (line 7: col 23) - Source: ... etal:use-macro="context/main_template/macros/master" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ - Arguments: repeat: {...} (0) template: <ImplicitAcquisitionWrapper base_view at 0x7f8ba8900820> modules: <instance - at 0x7f8bc49f8a28> here: <ImplicitAcquisitionWrapper analysisspec-10 at 0x7f8ba880f550> wrapped_repeat: <SafeMapping - at 0x7f8bab726ec0> user: <ImplicitAcquisitionWrapper - at 0x7f8ba89007d0> nothing: <NoneType - at 0x5580fb5421a0> target_language: <NoneType - at 0x5580fb5421a0> container: <ImplicitAcquisitionWrapper analysisspec-10 at 0x7f8ba880f550> default: <object - at 0x7f8bcfa59c00> root: <ImplicitAcquisitionWrapper Zope at 0x7f8babdd4a00> request: <instance - at 0x7f8ba79e17a0> traverse_subpath: <list - at 0x7f8ba83b8290> loop: {...} (3) context: <ImplicitAcquisitionWrapper analysisspec-10 at 0x7f8ba880f550> translate: <function translate at 0x7f8ba7fb9b18> macroname: master options: {...} (1)

**Comment by nascimf** [comment]
Hi, could you solve this problem? I am having the same problem

**Comment by nascimf** [comment]
Hi, could you solve this problem? I am having the same problem
