### ISSUE TITLE
Error when trying to create patient

### ISSUE THREAD

**Issue by ceeb3** [senaite/senaite.health#140]
senaite.core = 1.3.1
senaite.core.listing = 1.2.0
senaite.health = 1.2.1
senaite.impress = 1.2.1
senaite.lims = 1.3.1

Recently installed using Plone 4.3.18 on a Debian 9 (stretch) VM that was spun up specifically and only to run this. 

Creating a new patient from either the Patients step or from the Samples step generates the following error:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.FactoryTool, line 478, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 26, in _call
  Module Products.CMFFormController.FormController, line 384, in validate
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerValidator, line 58, in __call__
  Module Products.CMFFormController.Script, line 145, in __call__
  Module Products.CMFCore.FSPythonScript, line 127, in __call__
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 344, in _exec
  Module script, line 6, in validate_base
   - <FSControllerValidator at /senaite/patients/portal_factory/Patient/patient.2019-09-15.8076342369/validate_base>
   - Line 6
  Module Products.Archetypes.BaseObject, line 487, in validate
  Module Products.Archetypes.Schema, line 606, in validate
  Module Products.Archetypes.Field, line 345, in validate
  Module Products.Archetypes.Field, line 358, in validate_validators
  Module Products.validation.chain, line 136, in __call__
  Module bika.health.validators, line 76, in __call__
AttributeError: ClientPatientIDUnique

The ID i am entering is unique. I have tried numeric, alpha numeric, custom prefix and the behavior is the same.

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.health/pull/143
