### ISSUE TITLE
Stale JavaScripts in portal_javascripts

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.health#156]
## Steps to reproduce

From an upgraded version (pre 1.2.2), the following JavaScripts remain in the `portal_javascripts` tool:

- ++resource++bika.health.js/bika.health.analysisrequest.add.js
- ++resource++bika.health.js/bika.health.doctor.js

## Current behavior

Stale JavaScripts in `portal_javascripts` after 1.2.2 upgrade step

## Expected behavior

No Stale JavaScripts in `portal_javascripts` after 1.2.2 upgrade step

**Comment by xispa** [comment]
https://github.com/senaite/senaite.health/pull/170
