### ISSUE TITLE
Patient listings show wrong age

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.health#160]
## Steps to reproduce

Create a new patient and visit a few days after the patients listing

## Current behavior

The initial calculated age is shown

## Expected behavior

The currrent age is shown

## Screenshot (optional)

<img width="1186" alt="Patients" src="https://user-images.githubusercontent.com/713193/70978090-6d19e280-20af-11ea-9a11-b4374fddefa7.png">

**Comment by Espurna** [comment]
Should this be changed to "Age when the Sample was taken"?

**Comment by xispa** [comment]
I think the behavior is correct. It should display the Age when the sample was taken, at the age when performing the analyses made sense

**Comment by xispa** [comment]
Umm, sorry. Agree the age in **Patients** listing should display the current age
