### ISSUE TITLE
Cannot create Patient inside Client (content type not allowed)

### ISSUE THREAD

**Issue by rollomix92** [senaite/senaite.health#167]
## Steps to reproduce
I have a big problem I can't create samples because the patient is not shown when I insert the client.
same thing if I create a patient and check the client gives me an error.
## Screenshot (optional)

**Comment by xispa** [comment]
@rollomix92 can you please clarify what you mean by
- *patients problem in samples and client*
- *the patient is not shown when I insert the client* ?
- *I create a patient and check the client* ?
- what is exactly (traceback) you get when *the client gives me an error* ?

Please, give us more details in order to make our life easier when trying to reproduce the problem in section "Steps to reproduce" (a list of the actions you've done is very helpful, e.g. https://github.com/senaite/senaite.health/issues/96). Also, fill sections *Current behavior* and *Expected behavior* accordingly. Copy&pasting the traceback you get and a self-explanatory title of the ticket are quite useful too.

**Comment by rollomix92** [comment]
sorry, it was 3 hours that I was navigating in the code without solution.  
The problem is:
 when I insert the client in the creation of a sample, it does not give me the possibility to insert a patient already created.  
I think the problem is related to the fact that when I try to assign a customer from the individual patient it returns an error.  
as soon as I can I send the screen and I attach the error.  
I state that I have just performed a test installation on a virtual machine so I have the latest releases

**Comment by rollomix92** [comment]
## Steps to reproduce
select patient when create a sample request
## Current behavior
when I insert the client in the creation of a sample, it does not give me the possibility to select a patient already created, while if i select patient first, after select the client, patients disappear
I think the problem is related to the fact that when I try to assign a client from the individual patient it returns an error.

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 29, in _call
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 105, in __call__
  Module Products.CMFFormController.Script, line 145, in __call__
  Module Products.CMFCore.FSPythonScript, line 127, in __call__
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 344, in _exec
  Module script, line 1, in content_edit
   - <FSControllerPythonScript at /chimera/patients/P000001/content_edit>
   - Line 1
  Module Products.CMFCore.FSPythonScript, line 127, in __call__
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 344, in _exec
  Module script, line 12, in content_edit_impl
   - <FSPythonScript at /chimera/patients/P000001/content_edit_impl>
   - Line 12
  Module Products.Archetypes.BaseObject, line 645, in processForm
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module bika.health.subscribers.patient, line 40, in ObjectModifiedEventHandler
  Module OFS.CopySupport, line 332, in manage_pasteObjects
  Module OFS.CopySupport, line 208, in _pasteObjects
  Module Products.CMFCore.PortalFolder, line 421, in _verifyObjectPaste
ValueError: Disallowed subobject type: Patient




## Expected behavior
normal condition 
## Screenshot (optional)
![Screenshot from 2020-02-09 17-38-46](https://user-images.githubusercontent.com/60492879/74106159-66b25f00-4b64-11ea-9fd2-537c5edf30e5.png)
![Screenshot from 2020-02-09 17-39-17](https://user-images.githubusercontent.com/60492879/74106160-674af580-4b64-11ea-84b7-c3485c8d5554.png)

**Comment by xispa** [comment]
@rollomix92, seems that the creation of objects from `Patient` type cannot be created inside objects from type `Client`. Thanks for reporting, will open a PR. Meanwhile, you can fix the issue as follows:

1.- Login as admin user
2.- Go to *Site setup > Zope Management Interface* 
3.- Click to *portal_types (Controls the available content types in your portal)*
4.- Click to *Client (Client)*
5.- In field "Allowed content type", add "Patient" while leaving the rest selected (with Ctrl+click)
6.- Press *Save Changes*

**Comment by rollomix92** [comment]
Ok Solved, thanks.
