### ISSUE TITLE
Doctor field is always mandatory for Cases

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.health#178]
## Steps to reproduce

Uncheck the option in Site Setup:

![image](https://user-images.githubusercontent.com/7425587/77314289-a5ac0680-6d05-11ea-9746-c61d406405a0.png)

Doctor field is still compulsory.

![image](https://user-images.githubusercontent.com/7425587/77314164-6e3d5a00-6d05-11ea-9f38-89a28ec09cb9.png)

## Current behavior

Doctor field in Cases is always compulsory.

## Expected behavior

If the field is compulsory or not should depend on the site configuration.

## Screenshot (optional)

**Comment by xispa** [comment]
Cannot reproduce
