### ISSUE TITLE
The requirement ('beautifulsoup4==4.9.3') is not allowed by your [versions] constraint (4.11.1)

### ISSUE THREAD

**Issue by JackRomankiewicz** [senaite/senaite.health#206]
Hello,

I have a problem with Senaite 2.5.
Installs senaite 2.5 on new ubuntu 20.04 server. 
When trying to create an instance using the:
 
PYTHONHTTPSVERIFY=0 buildout 
 command, 
I receive this message:
"Error: The requirement ('beautifulsoup4==4.9.3') is not allowed by your [versions] constraint (4.11.1)"

My version section in  file buildout.cfg looks like this:

[versions]

zc.buildout =
setuptools =
Pillow = 5.1.0
cssselect2 = 0.2.2
soupsieve = 1.9.5
plone.recipe.unifiedinstaller = 5.2b1
buildout.sanitycheck = 1.0.2
collective.recipe.backup = 4.1.0

and requirements.txt l

setuptools==65.7.0
zc.buildout==3.0.1
pip==23.3.1
wheel==0.38.4

I am asking for help as to what is causing the error ?

**Comment by xispa** [comment]
Closing this one, `senaite.health` is a product for which we no longer provide support. For an installation of senaite 2.5.0, please ensure that `pip`, `setuptools`, and `zc.buildout` are available in a compatible version. These should be ok:

```
setuptools==42.0.2
zc.buildout==2.13.3
pip==20.1.1
```

These resources might be helpful as well:
- https://community.senaite.org/t/complete-setup-guide-step-by-step/137/71
- https://community.senaite.org/search?q=install
- https://community.senaite.org/search?q=buildout
