### ISSUE TITLE
Cannot deactivate Symptoms

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.health#51]
## Steps to reproduce
Awaiting creds for Naralabs demo. At /bika_setup/bika_symptoms in our installation

## Current behavior

Check boxes on the Active tab are not checking

![image](https://user-images.githubusercontent.com/1196034/36718314-faa4b100-1ba9-11e8-9dac-14633775050f.png)

They work on the All list, but there are no buttons

![image](https://user-images.githubusercontent.com/1196034/36718454-86e0e846-1baa-11e8-9735-689e0d9f4d95.png)

Neither can the user deactivate them on their views, say /bika_setup/bika_symptoms/symptom-1

## Expected behavior

Viva Chris Larsen, but one cannot have 68 Symptoms on the Case form:-)

**Comment by lemoene** [comment]
mmm, transition buttons on ARs too are missing, could be related to https://github.com/senaite/senaite.core/issues/667

![image](https://user-images.githubusercontent.com/1196034/36719900-05dcb0a4-1baf-11e8-8319-d007b271d691.png)

**Comment by xispa** [comment]
Cannot reproduce. Please confirm if you still experience this behavior
