### ISSUE TITLE
Cannot edit or create Analysis Profiles

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.health#54]
at https://health.bikalims.org/, i can confirm at naralabs demo but has not been sent creds yet

## Steps to reproduce

Navigate to existing An Profile

## Current behavior

Check boxes for selecting Analyses are inactive, also on new APs

![image](https://user-images.githubusercontent.com/1196034/37018962-0ec0e80a-211f-11e8-92fd-2030069b7313.png)

editing the AP elsewhere, eg the Title, produces a _Profile Analyses is required, please correct_  error on saving

![image](https://user-images.githubusercontent.com/1196034/37019037-56da74f8-211f-11e8-871d-7c583de84954.png)

## Expected behavior

Analysis Profile Analyses check boxes should be functional

**Comment by xispa** [comment]
Cannot reproduce. Please confirm

**Comment by lemoene** [comment]
My access request to the Naralabs Heralth demo twice went unanswered, would really like to confirm bug s there before logging them. Trying again

**Comment by xispa** [comment]
Oops, email sent with creds. Apologies!

**Comment by lemoene** [comment]
Not the place to report it, but i don't think I get these replies, searched spamboxes etc. I guessed my way into the demo thanks, but maybe test your demorequesting machine. Bests, l
