### ISSUE TITLE
Add Refelex Rule Folder Button creates a New Client

### ISSUE THREAD

**Issue by ronna** [senaite/senaite.health#55]
## Steps to reproduce
Login as a Lab Manager, navigate to Site Setup. Select Reflex Rule Folder, Click the Add Button

## Current behavior
The Add button takes you to the create New Client form

## Expected behavior
The Add button should create a New Reflex Rule folder

**Comment by xispa** [comment]
I've tried now and in my case, the system redirects me to the creation of an Invoice Batch. I'd say we have a problem here with a cookie or something related. Thanks for reporting!

**Comment by lemoene** [comment]
Not sure whether related, Add reflex rule button seen on Client Sample Points in LIMS

![image](https://user-images.githubusercontent.com/1196034/41152169-25975c60-6b13-11e8-9b05-d4f5a42a36da.png)

and leads to 

![image](https://user-images.githubusercontent.com/1196034/41152474-f7491a0a-6b13-11e8-83cd-5d8b3280057c.png)


global Sample Points ok


![image](https://user-images.githubusercontent.com/1196034/41152426-d55ed8b2-6b13-11e8-9b5e-e5a448806434.png)

**Comment by lemoene** [comment]
meh, i get the _Add reflex rule_ button on bikalims.org demos now, alos on Clients in Health. Separate issue?

![image](https://user-images.githubusercontent.com/1196034/41152680-b3c22956-6b14-11e8-9d2b-8c8e6bd4b433.png)
![image](https://user-images.githubusercontent.com/1196034/41152747-e162d5d6-6b14-11e8-8050-36d24155605b.png)

Passing this one on to Mike and Lunga

**Comment by Espurna** [comment]
Obsolete
