### ISSUE TITLE
Travis build badge renders to unknown

### ISSUE THREAD

**Issue by juangallostra** [senaite/senaite.health#79]
## Steps to reproduce

Go to the main page of `senaite.health`'s repository. The readme renders the Travis build badge but it is set as unknown.

## Current behavior

The Travis badge is rendered as unknown.

## Expected behavior

The Travis build badge is rendered with the latest build status of the repository.

I think any of you, @xispa or @ramonski, should activate the Travis integration.

## Screenshot (optional)

![seleccio_006](https://user-images.githubusercontent.com/9968427/39803307-f5ee4b68-5370-11e8-9603-c770dee142e6.png)

**Comment by ramonski** [comment]
Integrated in Travis CI
